[project]
name = "brittle_algorithm"
version = "0.1.0"
description = "This algorithm assesses the individual brittlness per image."
authors = [{ name = "Example Author" }]
readme = "README.md"
dependencies = [
    "aiverify-test-engine[all]",
    "albumentations==2.0.8",
    "augly==1.0.0",
    "imagecorruptions==1.1.2",
    "keras==3.12.0",
    "matplotlib==3.10.8",
    "nrtk==0.26.0",
    "numpy==1.26.4",
    "opencv-python-headless",
    "pandas==2.2.2",
    "pillow==10.4.0",
    "plotly==6.5.0",
    "scikit-image==0.25.2",
    "scikit-learn==1.5.2",
    "scipy==1.14.1",
    "torch>=2.9.1",
    "torchvision>=0.24.1",
    "tqdm==4.67.1"
]
requires-python = ">=3.10"
license = { file = "LICENSE" }
[tool.setuptools.packages.find]
include = ["brittle_algorithm"] 