apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  template:
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image }}
          env:
            {{- range .Values.items }} 
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
      restartPolicy: {{ .Values.restartPolicy }}
  backoffLimit: {{ .Values.backoffLimit }}